### ISSUE TITLE
修改前后端项目代码不生效

### ISSUE THREAD

**Issue by Nzybwzy** [Yin-Hongwei/music-website#101]
修改前后端项目代码不生效

**Comment by Yin-Hongwei** [comment]
> 修改前后端项目代码不生效

发一下具体截图

**Comment by Nzybwzy** [comment]
这个原因找到了 因为vscode打开整个项目 导致修改前端代码不生效 用三个窗口分别打开项目就可以了 
有新问题 图片404 找不到
按照文档配置完了 后端也启动了 库也连上了 然后图片404 
管理系统拿不到图片 前端拿不到MP3 感觉是路径问题 但不知道怎么改
http://localhost:8888//img/songListPic/wv2NdfZrUnLDSwk_kQoSZg==_109951163751040922.jpg 这是请求的图片地址 默认8888后有两个// 应该是不对的 去掉一个也不行 依然404

**Comment by Yin-Hongwei** [comment]
> 这个原因找到了 因为vscode打开整个项目 导致修改前端代码不生效 用三个窗口分别打开项目就可以了 有新问题 图片404 找不到 按照文档配置完了 后端也启动了 库也连上了 然后图片404 管理系统拿不到图片 前端拿不到MP3 感觉是路径问题 但不知道怎么改 http://localhost:8888//img/songListPic/wv2NdfZrUnLDSwk_kQoSZg==_109951163751040922.jpg 这是请求的图片地址 默认8888后有两个// 应该是不对的 去掉一个也不行 依然404

不管一个/还是两个/都不影响访问，看你资源本地在哪里，在对比实际地址看对不对
