### ISSUE TITLE
求接口文档（node重构后端）

### ISSUE THREAD

**Issue by 12345612138** [Yin-Hongwei/music-website#107]
老哥，我想用node重写一遍后端，请问接口文档方便分享一下嘛？935571063@qq.com您可以发俺邮箱里，还有就是我没了解过Spring Boot用文档中的启动服务方式启动不了，提示没有该指令（vscode的终端）用spring-boot:run可以，但跑着跑着不动了就

**Comment by Yin-Hongwei** [comment]
没有整理
