### ISSUE TITLE
报错，不知道什么问题，依赖安装不了这个

### ISSUE THREAD

**Issue by MRCAIFT** [Yin-Hongwei/music-website#114]
一直报这个错：Cannot find module 'babel-plugin-transform-vue-jsx'

**Comment by Yin-Hongwei** [comment]
> 一直报这个错：Cannot find module 'babel-plugin-transform-vue-jsx'

node 版本多少

**Comment by MRCAIFT** [comment]
v14.17.3，跟你的一样

**Comment by MRCAIFT** [comment]
> > 一直报这个错误：Cannot find module 'babel-plugin-transform-vue-jsx'
> 
> 节点版本多少


> > 一直报这个错误：找不到模块'babel-plugin-transform-vue-jsx'
> 
> 节点版本多少

v14.17.3，跟你的一样

**Comment by Yin-Hongwei** [comment]
> v14.17.3，和你一样

node_modules 和lock文件删了，执行yarn安装一下
