### ISSUE TITLE
图片和音乐都404,怎么解决

### ISSUE THREAD

**Issue by dongjmroot** [Yin-Hongwei/music-website#115]
![image](https://user-images.githubusercontent.com/80759175/156888015-40488528-9ecc-48a5-b78c-a23928fbd2fe.png)
![image](https://user-images.githubusercontent.com/80759175/156888049-5bea3796-8915-454a-8f40-adf7f073d7ab.png)

**Comment by AiClvGu** [comment]
我也遇到了这个问题

**Comment by AiClvGu** [comment]
您是怎么解决的呢？
