### ISSUE TITLE
注册没反应

### ISSUE THREAD

**Issue by SourceOnce** [Yin-Hongwei/music-website#121]
作者你好，部署完注册没反应，控制台输出
Uncaught (in promise) TypeError: Cannot destructure property 'proxy' of '(0 , vue__WEBPACK_IMPORTED_MODULE_0__.getCurrentInstance)(...)' as it is null.

**Comment by Yin-Hongwei** [comment]
> 作者你好，部署完注册没反应，控制台输出 Uncaught (in promise) TypeError: Cannot destructure property 'proxy' of '(0 , vue__WEBPACK_IMPORTED_MODULE_0__.getCurrentInstance)(...)' as it is null.

谢谢指出，已修复。
