### ISSUE TITLE
退出登录功能不好使

### ISSUE THREAD

**Issue by dingdang2619** [Yin-Hongwei/music-website#131]
<img width="184" alt="image" src="https://user-images.githubusercontent.com/31606192/160269279-389a7bc3-98f3-401c-9bfb-c816c26e0a4e.png">
<img width="592" alt="image" src="https://user-images.githubusercontent.com/31606192/160269284-ba45cae1-0451-42f1-9f54-b26003dfc417.png">
点击退出后跳转到error页面，network中也未发任何请求

**Comment by Yin-Hongwei** [comment]
已修复。更新一下 music-client/src/components/layouts/YinHeader.vue
