### ISSUE TITLE
无法登入管理界面和播放歌曲

### ISSUE THREAD

**Issue by Lihang99** [Yin-Hongwei/music-website#14]
数据库的配置信息已经修改为本机 按照您的文件结构将data下载解压后放入了项目  歌单歌曲啥的都能加载出来 就是无法播放 而且用数据库中有的管理员账号admin 密码123点击登录没有反应 请问是怎么一回事呢

**Comment by Yin-Hongwei** [comment]
前端项目有两个，一个在client下，一个在server下，你用的那个账号是登server下的，那个是管理员登录的。登client你用账号：Yin，密码：123，试一下，或者你可以注册一下。音乐播放不了可能的原因是你后端路径映射那里没有配置对，配一下试试。

**Comment by Zifengest** [comment]
我也是这样，前台运行没问题，后台点击登录没反应，看代码是能出密码错误提示的，可是无论输入什么，点登录都没提示

**Comment by Yin-Hongwei** [comment]
> 我也是这样，前台运行没问题，后台点击登录没反应，看代码是能出密码错误提示的，可是无论输入什么，点登录都没提示

之前封装请求有点问题，问题已修复，更下代码试试。

**Comment by Yin-Hongwei** [comment]
> 数据库的配置信息已经修改为本机 按照您的文件结构将data下载解压后放入了项目 歌单歌曲啥的都能加载出来 就是无法播放 而且用数据库中有的管理员账号admin 密码123点击登录没有反应 请问是怎么一回事呢

谢谢指出，之前封装请求有点问题，问题已修复，更下代码试试。

**Comment by Zifengest** [comment]
> > 我也是这样，前台运行没问题，后台点击登录没反应，看代码是能出密码错误提示的，可是无论输入什么，点登录都没提示
> 
> 之前封装请求有点问题，问题已修复，更下代码试试。

嗯，可以进了

**Comment by Yin-Hongwei** [comment]
> > > 我也是这样，前台运行没问题，后台点击登录没反应，看代码是能出密码错误提示的，可是无论输入什么，点登录都没提示
> > 
> > 
> > 之前封装请求有点问题，问题已修复，更下代码试试。
> 
> 嗯，可以进了

好的😄
