### ISSUE TITLE
大佬最新代码无法上传歌曲，麻烦您看一下，是我配置问题吗

### ISSUE THREAD

**Issue by YUnanbowan** [Yin-Hongwei/music-website#147]
![9FA3_W$%~SCQ95 7D(BZT0M](https://user-images.githubusercontent.com/101042768/163408966-3ccf334d-ddf9-4455-84ab-3a7b327fdd00.png)
![1ZTW5K0YFLZ%Q6{OT6P@~_W](https://user-images.githubusercontent.com/101042768/163408999-827026a7-80eb-4c49-be6d-7601cc7904a8.png)

**Comment by Yin-Hongwei** [comment]
重新拉下代码，已修复
