### ISSUE TITLE
springboot:SpringBoot项目启动成功,但无法访问且提示404

### ISSUE THREAD

**Issue by suits22** [Yin-Hongwei/music-website#149]
作者您好,本人新手想学习一下项目
但是打开music-server 可以运行但是页面报404

![1](https://user-images.githubusercontent.com/61674277/163569693-3dbdb970-4e62-4bfd-8f0e-04e9db5c66fc.png)

: No mapping for GET /
![FGJIK3{0SY2OLU9JNFZ}GP4](https://user-images.githubusercontent.com/61674277/163569767-bb1df9b7-d28f-4ddc-aa09-094fecef0a0d.png)

**Comment by Yin-Hongwei** [comment]
readme里有些怎么运行，你前端项目启动了吗？

**Comment by suits22** [comment]
您好,前端项目启动了 ,但是学着打开music server 就有问题 :mvn -run-spring-boot  :run 
![image](https://user-images.githubusercontent.com/61674277/163783198-24f80276-fe5c-4938-9c83-4b485a91ced1.png)
![image](https://user-images.githubusercontent.com/61674277/163783331-e32c0531-d72e-4165-bcf7-4cc74b79e748.png)
![image](https://user-images.githubusercontent.com/61674277/163783372-53a72ee3-ebbd-4fab-af53-2688295348ae.png)

**Comment by Yin-Hongwei** [comment]
mvn spring-boot:run
