### ISSUE TITLE
ConsumerService少个conmentUser函数

### ISSUE THREAD

**Issue by wwwhahahaha** [Yin-Hongwei/music-website#15]
图片传不上来，您看一下吧，在LoginController的第234行显示函数丢失，

**Comment by wwwhahahaha** [comment]
还有105行，可能是您之前清理函数时没有清理干净

**Comment by Yin-Hongwei** [comment]
> 图片传不上来，您看一下吧，在LoginController的第234行显示函数丢失，

LoginController？？这个类我换掉了，应该没有哇？麻烦图片发我邮箱我看一下yinhongwei96@126.com
