### ISSUE TITLE
一些个人问题

### ISSUE THREAD

**Issue by Kowayi** [Yin-Hongwei/music-website#154]
我是一个后端的初学者请问作者大大:

我现在所学的ssm框架可以仿照着您这个项目自己做个吗?
因为我想运用您的前段界面，前几天也是去学了vue，所以您有没有什么建议呢。

**Comment by Yin-Hongwei** [comment]
不管要去做前端或后端，对全栈的东西了解一些对自己都很有帮助，但是决定了一个方向，就多花时间去专研那个方向的东西，这个项目后端比较简单，前端会相对复杂一些，初学的话后端可以看看，但想要在有一定高度就多去补充专业知识，在找一些偏后端，运用更多后端技术的项目来练习，或者自己做一个项目
