### ISSUE TITLE
歌曲下载只有1kb，不能播放

### ISSUE THREAD

**Issue by danfeng465** [Yin-Hongwei/music-website#155]
![image](https://user-images.githubusercontent.com/86083509/164165383-013f96b6-c188-4133-acde-33e9d3abe469.png)
没有报错

**Comment by danfeng465** [comment]
另外想知道下载请求对应的后端接口是在哪里，谢谢

**Comment by Yin-Hongwei** [comment]
> ![image](https://user-images.githubusercontent.com/86083509/164165383-013f96b6-c188-4133-acde-33e9d3abe469.png) 没有报错

音乐可能损毁了，后端重新替换一下

**Comment by Yin-Hongwei** [comment]
> 另外想知道下载请求对应的后端接口是在哪里，谢谢

去两个前端的 src/api/index.ts 看吧

**Comment by yyj-xx** [comment]
这个问题怎么解决我这边也有这个问题
