### ISSUE TITLE
请问一下遇到的一些问题

### ISSUE THREAD

**Issue by tiancheng666** [Yin-Hongwei/music-website#157]
1，为什么同一个用户可以对同一个歌单进行无数次的点赞
2，管理员对用户收藏的歌曲不能删除
2，用户收藏歌曲，用户不能取消掉

**Comment by Roroldo** [comment]
第二个需求我觉得没必要，第一个你可以试试用 redis 解决重复点赞的问题，第三个也好解决，就是后端接受收藏请求之前先判断一下是否收藏，有的话就删除，没有就收藏

**Comment by Yin-Hongwei** [comment]
1、这个bug目前还没改
2、只是前端设置了禁用，去掉disabled就行
3、更新下代码
