### ISSUE TITLE
项目运行起来以后，后台登录不了

### ISSUE THREAD

**Issue by jidangen** [Yin-Hongwei/music-website#160]
点击登录就弹窗，弹窗里啥也没有，看了一下也没有报错
<img width="444" alt="image" src="https://user-images.githubusercontent.com/46592841/164369374-5a071cb4-23cb-4707-a961-6610bbca8d23.png">

**Comment by Yin-Hongwei** [comment]
> 点击登录就弹窗，弹窗里啥也没有，看了一下也没有报错 <img alt="image" width="444" src="https://user-images.githubusercontent.com/46592841/164369374-5a071cb4-23cb-4707-a961-6610bbca8d23.png">

F12打开控制台，进network发一下收到的http消息是啥

**Comment by jidangen** [comment]
<img width="546" alt="image" src="https://user-images.githubusercontent.com/46592841/164439681-870fd773-0de7-435a-a703-7369f6f076d8.png">

**Comment by Yin-Hongwei** [comment]
点名称下的 status

**Comment by jidangen** [comment]
显示登录成功了
{msg: "登录成功", code: 1}
code: 1
msg: "登录成功"

**Comment by Yin-Hongwei** [comment]
{
code: 200
data: null
message: "登录成功"
success: true
type: "success"
}
更新下代码吧，最新的结构是这样的，可能之前有bug

**Comment by jidangen** [comment]
好的，感谢回复
