### ISSUE TITLE
图片加载不出来，路径输出如图

### ISSUE THREAD

**Issue by Edgar1115** [Yin-Hongwei/music-website#164]
![问题](https://user-images.githubusercontent.com/78690904/164956132-8afc3af3-d0e3-4890-ab1b-efdad4f7db9c.png)
![输出路径](https://user-images.githubusercontent.com/78690904/164956131-4056e5c5-aa87-4d25-9a02-cad0ae75a0ea.png)

**Comment by Roroldo** [comment]
你先按照文档把资源放在对应目录吧
