### ISSUE TITLE
请求api过后，会发起http://localhost:8888请求，报错为404

### ISSUE THREAD

**Issue by Matt23-star** [Yin-Hongwei/music-website#167]
在运行了后端server 以及前端client过后，登录想访问歌手目录，但是出现了下面的报错，数据可以获取到，但是前端页面中无法展示。请问怎么解决呀。
![image](https://user-images.githubusercontent.com/67894824/166135980-a1e51dcd-b080-4816-a096-e8584d1385c3.png)

**Comment by YuanJIN00** [comment]
你好 请问你解决了吗

**Comment by Matt23-star** [comment]
> 你好 请问你解决了吗

解决了，重新更新一下代码就ok了
