### ISSUE TITLE
管理用户收藏无法删除

### ISSUE THREAD

**Issue by gky86886** [Yin-Hongwei/music-website#173]

**Comment by gky86886** [comment]
![12314](https://user-images.githubusercontent.com/57277917/167405251-81a76b71-6a3f-4443-b52a-dee2c5809ba4.jpg)

**Comment by gky86886** [comment]
用户头像也修改不了了 呜呜呜

**Comment by Yin-Hongwei** [comment]
<img width="1313" alt="iShot_2022-05-10_10 11 39" src="https://user-images.githubusercontent.com/37996435/167528484-e3c2104a-2e4f-4adb-9085-663d9f07e810.png">
