### ISSUE TITLE
上传歌曲失败但是显示的却是这个

### ISSUE THREAD

**Issue by jidangen** [Yin-Hongwei/music-website#174]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/46592841/167766315-193c0e72-4ee9-409b-8799-2958ff5588ed.png">

另外上传歌曲的限制在哪里可以改呢

**Comment by Yin-Hongwei** [comment]
前后端都有了，有两处。你代码里搜一下，搜MB

**Comment by jidangen** [comment]
找到了，感谢
