### ISSUE TITLE
几个小bug 

### ISSUE THREAD

**Issue by gky86886** [Yin-Hongwei/music-website#176]
自己太菜了..解决不了.
![删除bug](https://user-images.githubusercontent.com/57277917/167988631-1d557bd6-8235-4759-9ef8-39ac777f45b8.gif)
![添加歌曲bug](https://user-images.githubusercontent.com/57277917/167988643-4ceecef0-82b8-45c5-a2fa-c71c4383a9d2.gif)
![点赞bug](https://user-images.githubusercontent.com/57277917/167988651-f2ba45d8-1cff-43c7-8cd8-f9272e0f1fbe.gif)

**Comment by Yin-Hongwei** [comment]
已修复，更新下代码。
