### ISSUE TITLE
这里挂侵权地址，有发现的欢迎补充，谢谢

### ISSUE THREAD

**Issue by Yin-Hongwei** [Yin-Hongwei/music-website#18]
### 1、

- B站：https://space.bilibili.com/356629729?spm_id_from=333.788.b_765f7570696e666f.1

![](https://tva1.sinaimg.cn/large/007S8ZIlly1gemeqxzs27j310i0iutu4.jpg)

- csdn：https://blog.csdn.net/qq_40985788/

![](https://tva1.sinaimg.cn/large/007S8ZIlly1gemeuatiagj31740oykaq.jpg)

**Comment by aassshuobao** [comment]
**这些人真的可恶！拿别人作品卖钱 真恶心！**

**Comment by Vicent-wong** [comment]
支持，发现一个举报一个，这个人其他的项目还不知道是从哪里偷来的，那些被偷的技术博主估计也没有发现

**Comment by Yin-Hongwei** [comment]
> 支持，发现一个举报一个，这个人其他的项目还不知道是从哪里偷来的，那些被偷的技术博主估计也没有发现

对啊，我也是有个热心网友和我说的，这个人贼不要脸了。。。
