### ISSUE TITLE
用户和管理员图片加载不出来

### ISSUE THREAD

**Issue by lemonil** [Yin-Hongwei/music-website#181]
![image](https://user-images.githubusercontent.com/105693829/168757845-fb68c0c4-d527-4afe-a220-b3e3f75b57b7.png)
图片资源位置应该是正常的，不知道该如何解决
![image](https://user-images.githubusercontent.com/105693829/168757953-3be8612f-8945-4808-85fd-b51633a3d95f.png)

**Comment by Yin-Hongwei** [comment]
把user.jpg放到avatorImages目录里就行了
