### ISSUE TITLE
music-server运行后出现异常

### ISSUE THREAD

**Issue by Vilote** [Yin-Hongwei/music-website#193]
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Jun 29 09:44:36 GMT+08:00 2022
There was an unexpected error (type=Not Found, status=404).
No message available
启动项目后，打开浏览器页面出现上述问题，在终端出现WARN PageNotFound:1278 - No mapping for GET

**Comment by Uranusual** [comment]
解决了吗? 
同样的问题

**Comment by Uranusual** [comment]
一模一样的问题,作者知道是哪里出问题了吗?
