### ISSUE TITLE
后台报错，特别奇怪的错误，这个是什么请款了 

### ISSUE THREAD

**Issue by shiliu001** [Yin-Hongwei/music-website#197]
八月 04, 2022 12:11:03 下午 org.apache.catalina.core.StandardService startInternal
信息: Starting service [Tomcat]
八月 04, 2022 12:11:03 下午 org.apache.catalina.core.StandardEngine startInternal
信息: Starting Servlet engine: [Apache Tomcat/9.0.56]
八月 04, 2022 12:11:03 下午 org.apache.catalina.core.ApplicationContext log
信息: Initializing Spring embedded WebApplicationContext

**Comment by suqi37** [comment]
我也报这个错误,请问你解决了吗
