### ISSUE TITLE
按性别来显示歌手信息返回的数据是空的

### ISSUE THREAD

**Issue by Mzaxd** [Yin-Hongwei/music-website#209]
小优化集合下面提到的一个问题，原因是SingerServiceImpl下singerOfSex方法的queryWrapper条件字段写错了 应该是"sex" 源码中是"name" 
![image](https://user-images.githubusercontent.com/62539735/189365678-93b60771-9755-421e-af55-ef134f8d0a08.png)

**Comment by Yin-Hongwei** [comment]
已修复 👏
