### ISSUE TITLE
建议写个详细的开发文档

### ISSUE THREAD

**Issue by Zifengest** [Yin-Hongwei/music-website#22]
项目确实不错，要是怕别人倒卖可以别上传数据库，整个线上的演示，没有文档学起来还是很不方便

**Comment by Yin-Hongwei** [comment]
> 项目确实不错，要是怕别人倒卖可以别上传数据库，整个线上的演示，没有文档学起来还是很不方便

之前没想到这么多。因为现在已经上传了，百度云显示下载的有300多，要是现在把数据库删了，有的人刚好就能拿出来卖。。所以没办法删了现在。
开发文档有，精力有限写了个大概，地址在项目的“项目说明”里。

**Comment by Yin-Hongwei** [comment]
> 项目确实不错，要是怕别人倒卖可以别上传数据库，整个线上的演示，没有文档学起来还是很不方便

谢谢😄
