### ISSUE TITLE
上传图片，传递给后端的时候，后端报错，传过来的为null

### ISSUE THREAD

**Issue by maimaicuizhiji** [Yin-Hongwei/music-website#243]
上传图片，传递给后端的时候，后端报错，传过来的为null
`<el-upload  :action="uploadPic(scope.row.id)"
                      :on-success="handleAvatarSuccess"
                      :before-upload="beforeAvatarUpload"
                      :show-file-list="false"
                      name="avatar"
          >
            <el-button size="small">更新图片</el-button>
          </el-upload>`

`public Object updateSingerPic(@RequestParam("avatar") MultipartFile file, @RequestParam("id") int id) {
        String fileName = System.currentTimeMillis() + file.getOriginalFilename();
        String filePath = System.getProperty("user.dir") + System.getProperty("file.separator") + "img"
                + System.getProperty("file.separator") + "singerPic";
        File file1 = new File(filePath);
        if (!file1.exists()) {
            file1.mkdir();
        }
    }`

**Comment by panliang-rm** [comment]
请问解决了吗，我的也是更新图片不行

**Comment by maimaicuizhiji** [comment]
解决了，github交流不太方便，加个qq吧，578070863
