### ISSUE TITLE
请问楼主Search组件中handleChangeView方法后面传递的数字有什么作用吗？

### ISSUE THREAD

**Issue by DDFXulei** [Yin-Hongwei/music-website#27]
```JavaScript
handleChangeView('Songs', 0)
handleChangeView('SongLists', 1)
```
这个0和1有什么意义呢？

**Comment by Yin-Hongwei** [comment]
> ```js
> handleChangeView('Songs', 0)
> handleChangeView('SongLists', 1)
> ```
> 
> 这个0和1有什么意义呢？

去掉吧，没用。
之前好像做过什么处理来，后来去掉了很多冗余的东西忘删了。
