### ISSUE TITLE
### 1、图片、音乐加载失败

### ISSUE THREAD

**Issue by wht15116532585** [Yin-Hongwei/music-website#275]
### 1、图片、音乐加载失败

把 music-website/music-server 目录下的 img、song 目录移动到 music-website 目录。**【拉的最新的代码可忽略】**

### 2、新注册用户头像加载不出来

在 music-website/music-server/img/avatorImages 目录下放一张叫 user.jpg 的图片。

### 3、轮播图加载失败

如果是之前拉的代码，现在更新后轮播图加载不出来，需要更新数据库信息（重新导入`music-website/music-server/sql`  文件）；并且去 【链接: https://pan.baidu.com/s/1Qv0ohAIPeTthPK_CDwpfWg 提取码: gwa4 】将 swiper 压缩包放到本地 img 目录下（详情见 readme 安装步骤截图）。**【拉的最新的代码可忽略】**

### 4、音乐播放不了

可能是音乐损毁了，重新更换一下音乐资源。

_Originally posted by @Yin-Hongwei in https://github.com/Yin-Hongwei/music-website/discussions/182_

**Comment by nanshaws** [comment]
音乐下载问题，被我解决了，就是单纯的前端没有获取到数据，音乐播放我这边倒是没什么问题

**Comment by wht15116532585** [comment]
网络请求的地址是一串字符，音乐播放不了，也下载不了


素以
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yin-Hongwei/music-website"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月13日(星期三) 下午2:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Yin-Hongwei/music-website] ### 1、图片、音乐加载失败 (Issue #275)





 
音乐下载问题，被我解决了，就是单纯的前端没有获取到数据，音乐播放我这边倒是没什么问题

**Comment by nanshaws** [comment]
网络请求的地址是一串字符，是因为我们采用的是blob模式，至于您说的音乐播放不了，这个要在音乐管理页面手动添加音乐的，只有添加完音乐才可以播放，原先的下载是有点问题，已经被我修复好了










                       
原始邮件
                       
                     

发件人："wht15116532585"< ***@***.*** &gt;;

发件时间：2024/3/13 14:35

收件人："Yin-Hongwei/music-website"< ***@***.*** &gt;;

抄送人："cover"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

主题：Re: [Yin-Hongwei/music-website] ### 1、图片、音乐加载失败 (Issue #275)




 网络请求的地址是一串字符，音乐播放不了，也下载不了 
 
 
 素以 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "Yin-Hongwei/music-website"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2024年3月13日(星期三) 下午2:27 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [Yin-Hongwei/music-website] ### 1、图片、音乐加载失败 (Issue #275) 
 
 
 
 
 
   
 音乐下载问题，被我解决了，就是单纯的前端没有获取到数据，音乐播放我这边倒是没什么问题

**Comment by wht15116532585** [comment]
好的，谢谢！


素以
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yin-Hongwei/music-website"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月13日(星期三) 下午2:40
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Yin-Hongwei/music-website] ### 1、图片、音乐加载失败 (Issue #275)





 网络请求的地址是一串字符，是因为我们采用的是blob模式，至于您说的音乐播放不了，这个要在音乐管理页面手动添加音乐的，只有添加完音乐才可以播放，原先的下载是有点问题，已经被我修复好了 
 
 
 
 
 
 
 
 
 
 
                         
 原始邮件 
                         
                       
 
 发件人："wht15116532585"< ***@***.*** &amp;gt;; 
 
 发件时间：2024/3/13 14:35 
 
 收件人："Yin-Hongwei/music-website"< ***@***.*** &amp;gt;; 
 
 抄送人："cover"< ***@***.*** &amp;gt;;"Comment"< ***@***.*** &amp;gt;; 
 
 主题：Re: [Yin-Hongwei/music-website] ### 1、图片、音乐加载失败 (Issue #275) 
 
 
 
 
  网络请求的地址是一串字符，音乐播放不了，也下载不了  
   
   
  素以  
  ***@***.***  
   
   
   
  &amp;amp;nbsp;  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "Yin-Hongwei/music-website"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2024年3月13日(星期三) 下午2:27  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [Yin-Hongwei/music-website] ### 1、图片、音乐加载失败 (Issue #275)  
   
   
   
   
   
     
  音乐下载问题，被我解决了，就是单纯的前端没有获取到数据，音乐播放我这边倒是没什么问题
