### ISSUE TITLE
歌词如何显示的问题

### ISSUE THREAD

**Issue by YinzeZhang** [Yin-Hongwei/music-website#29]
您好，请问您项目中的歌词滚动显示功能应该如何使用，我这边其它的功能都能正常使用，就是没有找到歌词滚动显示功能应该如何使用，前端没有看到相关的接口。

**Comment by Yin-Hongwei** [comment]
> 您好，请问您项目中的歌词滚动显示功能应该如何使用，我这边其它的功能都能正常使用，就是没有找到歌词滚动显示功能应该如何使用，前端没有看到相关的接口。

这个你先去数据库看一下歌曲对应的歌词放的什么数据，歌词不单单只有歌词，每句话前面都有对应的时间，前端会对歌词解析，解析后根据歌词前面记录的时间判断显示哪一句。
解析歌词的函数是 mixins/index下的parseLyric函数。控制显示哪一句在Lyric.vue中

**Comment by YinzeZhang** [comment]
感谢您的回复，我已经解决了我的问题，我之前是因为没找到歌词滚动显示功能应该如何使用，现在我发现了，点击播放区的歌曲图片可以进入歌词滚动界面，我之前没发现播放区的歌曲图片能点。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"尹宏伟"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月26日(星期五) 下午4:08
收件人:&nbsp;"Yin-Hongwei/music-website"<music-website@noreply.github.com&gt;;
抄送:&nbsp;"张胤泽"<1285763952@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Yin-Hongwei/music-website] 歌词如何显示的问题 (#29)





  
您好，请问您项目中的歌词滚动显示功能应该如何使用，我这边其它的功能都能正常使用，就是没有找到歌词滚动显示功能应该如何使用，前端没有看到相关的接口。
  
这个你先去数据库看一下歌曲对应的歌词放的什么数据，歌词不单单只有歌词，每句话前面都有对应的时间，前端会对歌词解析，解析后根据歌词前面记录的时间判断显示哪一句。
 解析歌词的函数是 mixins/index下的parseLyric函数。控制显示哪一句在Lyric.vue中

**Comment by Yin-Hongwei** [comment]
解决了就好，我想错了，哈哈哈哈
