### ISSUE TITLE
歌词只有一行时不是居中的，大伙会这样吗

### ISSUE THREAD

**Issue by zhemozhiwangddd** [Yin-Hongwei/music-website#291]
前端不太熟悉，自己试着调整了很多样式都没用，前来求助下，不知道大家有没有一样的问题
![image](https://github.com/Yin-Hongwei/music-website/assets/77574663/1ebec6bb-8979-4ce9-b293-8d15ee6b9017)

**Comment by zhemozhiwangddd** [comment]
还是没搞懂，一行靠左，两行就居中了，强迫症好难受
![image](https://github.com/Yin-Hongwei/music-website/assets/77574663/31ed3db4-3a60-413f-a83e-8f43a8d9c088)
![image](https://github.com/Yin-Hongwei/music-website/assets/77574663/9519ef3d-447c-4d79-acc2-12bfc6de8567)

**Comment by zhemozhiwangddd** [comment]
解决了，是因为歌词ul元素相对于父元素不是居中显示的，按下图加这两行就好了。作者也可以改一下，强迫症很难受
![image](https://github.com/Yin-Hongwei/music-website/assets/77574663/9c5b5da0-dabe-47a0-9865-17e924a1d890)

**Comment by nanshaws** [comment]
> 解决了，是因为歌词ul元素相对于父元素不是居中显示的，按下图加这两行就好了。作者也可以改一下，强迫症很难受 ![image](https://private-user-images.githubusercontent.com/77574663/332644642-9c5b5da0-dabe-47a0-9865-17e924a1d890.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNzYwMjEsIm5iZiI6MTcyMTM3NTcyMSwicGF0aCI6Ii83NzU3NDY2My8zMzI2NDQ2NDItOWM1YjVkYTAtZGFiZS00N2EwLTk4NjUtMTdlOTI0YTFkODkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDA3NTUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMDdiMTJmOGE3ZTg4ODU0NTM0ZTJlZDUzZTE3OTcxNWQ0NGFkMDQ0MGI3ZDE1ZTc4NmFlMjMwYjJiMjY4YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KGOZycj8_8ru2U3dyydlCnKPsCKFA5mQDkZq_L6hrvw)

okok，改了
