### ISSUE TITLE
歌曲的上传下载功能怎么使用 好像没有

### ISSUE THREAD

**Issue by liu347881922** [Yin-Hongwei/music-website#3]
歌曲的上传下载功能怎么使用 好像没有

**Comment by liu347881922** [comment]
测试中发现  歌单删除和歌单内歌曲删除存在获取id为空和未定义的情况
java.lang.NumberFormatException: For input string: "undefined"
java.lang.NumberFormatException: For input string: ""
![ZOKR4XD178}Y6$JHVUB5RLV](https://user-images.githubusercontent.com/35589383/64846719-e41e8580-d63f-11e9-9c65-d0accd829d7a.png)

**Comment by Yin-Hongwei** [comment]
前端获取ID的数组不对，还有后端有个接口忘写了，我有点事儿，晚上改，谢谢指出，哈哈哈

**Comment by Yin-Hongwei** [comment]
问题修复了，已经push了，顺便重写了下歌曲信息那个组件，引用vue-aplayer组件用在这里太吃内存了，还有调整了下代码和项目结构。

**Comment by liu347881922** [comment]
收到  上传音乐那里推荐SongController的 addSong那歌词添加数据库时改为 String lyric = "[00:00:00]"+req.getParameter("lyric").trim();   不然没添加歌词时会因为没有[00:00:00]显示不出歌曲，我这边测试是这样的  ，不知道大佬那会不会有这情况

**Comment by Yin-Hongwei** [comment]
哈哈哈，是的，谢谢指出！------------------ 原始邮件 ------------------
发件人: "bigHub"<notifications@github.com>
发送时间: 2019年9月14日(星期六) 中午12:18
收件人: "Yin-Hongwei/music-website"<music-website@noreply.github.com>;
抄送: "尹宏伟"<3374461366@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Yin-Hongwei/music-website] 歌曲的上传下载功能怎么使用 好像没有 (#3)



收到  上传音乐那里推荐SongController的 addSong那歌词添加数据库时改为 String lyric = "[00:00:00]"+req.getParameter("lyric").trim();   不然没添加歌词时会因为没有[00:00:00]显示不出歌曲，我这边测试是这样的  ，不知道大佬那会不会有这情况
 
&mdash;

**Comment by Yin-Hongwei** [comment]
那个问题是之前前端解析歌词导致的问题，我改前端解析方式了，所以后端可以不动。
