### ISSUE TITLE
为什么我后端项目启动会抱这个错，求解答

### ISSUE THREAD

**Issue by wzq421** [Yin-Hongwei/music-website#34]
Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.1.1.RELEASE:run (default-cli) on project demo: An exception occurred while running. null: InvocationTargetException: Connector configured to listen on port 8888 failed to start -> [Help 1]

**Comment by Yin-Hongwei** [comment]
还有其他报错信息吗？

**Comment by wzq421** [comment]
谢谢。已经解决了



---原始邮件---
发件人: "尹宏伟"<notifications@github.com&gt;
发送时间: 2020年7月28日(周二) 凌晨0:37
收件人: "Yin-Hongwei/music-website"<music-website@noreply.github.com&gt;;
抄送: "wzq421"<649875526@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Yin-Hongwei/music-website] 为什么我后端项目启动会抱这个错，求解答 (#34)




 
还有其他报错信息吗？
