### ISSUE TITLE
项目都能运行，但是图片音乐资源都加载不出来

### ISSUE THREAD

**Issue by Xw3C** [Yin-Hongwei/music-website#36]
路径也改了
"file:G:\\Study\\IntellijIDEA\\MusicProgram\\new\\music-website-master\\music-website-master\\music-server\\img\\songListPic"

**Comment by Yin-Hongwei** [comment]
file:G:\\Study\\IntellijIDEA\\MusicProgram\\new\\music-website-master\\music-website-master\\music-server\\img\\songListPic\\

**Comment by Yin-Hongwei** [comment]
1、是两个\
2、XXXXXXXXXsongListPic的后面也要加两个\

**Comment by Xw3C** [comment]
感谢，后面少加了\\
