### ISSUE TITLE
music-client运行不起来

### ISSUE THREAD

**Issue by cryptopunkg** [Yin-Hongwei/music-website#43]
您好，我在music-client目录下运行npm install安装了所有的依赖包，但是尝试npm run dev的时候报这样的错误。
错误：
![image](https://user-images.githubusercontent.com/18069502/103543461-89b2d380-4ed9-11eb-8f61-8807f88e0ea1.png)

These dependencies were not found:

* vue-router/types in ./src/main.js
* vue/types in ./src/main.js
* vuex/types in ./src/main.js, ./src/mixins/index.js

这几个包我看了以下是已经安装在node_modules文件夹下面的，
![image](https://user-images.githubusercontent.com/18069502/103543529-a3541b00-4ed9-11eb-8505-2dd0a79b939b.png)

不知道为什么vue没办法识别并成功引入呢？

**Comment by Yin-Hongwei** [comment]
node、npm版本多少，可能是版本太低了

**Comment by Guomoon** [comment]
![image](https://user-images.githubusercontent.com/18069502/103982236-10a7ca80-51be-11eb-9b71-b3f09879f913.png)
node和npm都是最新版本的，我怀疑是不是不能识别typescript文件，是不是要做一些额外配置呢？

**Comment by Guomoon** [comment]
![image](https://user-images.githubusercontent.com/18069502/103982311-3634d400-51be-11eb-91c6-18230523299a.png)

**Comment by Yin-Hongwei** [comment]
你把node_modules和package-lock.json删了重新npm install一下呢
