### ISSUE TITLE
MyBatis Generator生成了mapper文件之后，有些查询的方法是之后加进去的吗？

### ISSUE THREAD

**Issue by gimwu** [Yin-Hongwei/music-website#50]
自己尝试了下MyBatis Generator这个包运行效果，有些需要的查询方法没有生成出来，想请问下楼主，所有的查询方法都是通过MyBatis Generator生成的吗？还是说有一部分方法是MyBatis Generator生成后再手动写进mapper里的？

**Comment by Yin-Hongwei** [comment]
是的，只能生成一部分，其他的还需要自己写。
