### ISSUE TITLE
修改头像后，头像变为透明

### ISSUE THREAD

**Issue by axh2018** [Yin-Hongwei/music-website#53]
设置中，修改头像后，头像变为透明。
而且，我已经按照read配置好了资源路径，前台图片还是显示不出来。

**Comment by Yin-Hongwei** [comment]
发一下你配的路径

**Comment by axh2018** [comment]
![Snipaste2021-03-18-17-57-42](https://user-images.githubusercontent.com/58505743/111607724-7d20f480-8813-11eb-94d6-7556c00aa88e.png)
安装readme配置的

**Comment by axh2018** [comment]
![Snipaste2021-03-18-21-21-08](https://user-images.githubusercontent.com/58505743/111632867-e0b91b00-882f-11eb-971a-4dc1833ec795.png)
按照readme配置的

**Comment by Yin-Hongwei** [comment]
路径不对，少了file，你看看下配置里写的

**Comment by axh2018** [comment]
#### 感谢~ 已解决，不过修改头像后，原图比例不是1：1的话，显示会有问题。下面会缺一块。
![bug](https://user-images.githubusercontent.com/58505743/111784213-17596900-88f6-11eb-8b99-6d3c5146d673.png)

![imgsdzxages](https://user-images.githubusercontent.com/58505743/111784238-22ac9480-88f6-11eb-8c4d-1e7daccc56cd.jpg)
