### ISSUE TITLE
搜索栏一直无法查询到歌曲

### ISSUE THREAD

**Issue by Rain-ziyu** [Yin-Hongwei/music-website#54]
![image](https://user-images.githubusercontent.com/70049441/115360155-f2585e80-a1f1-11eb-9db6-103daecbb008.png)

**Comment by Yin-Hongwei** [comment]
你数据库版本是多少？

**Comment by Rain-ziyu** [comment]
![image](https://user-images.githubusercontent.com/70049441/117531953-a42bc380-b017-11eb-9d1c-0825c5c4186d.png)
5.7.27

**Comment by Yin-Hongwei** [comment]
你在评论里随便写点东西，然后去数据库看看保存的数据是不是乱码，是的话升一下mysql版本，我感觉是版本问题
