### ISSUE TITLE
跳转失败

### ISSUE THREAD

**Issue by gz-j** [Yin-Hongwei/music-website#60]
用户端登录后 跳转主页失败，交换了两行代码顺序好像可以了。也可能是我电脑问题/music-client/src/pages/LoginIn.vue
![image](https://user-images.githubusercontent.com/59046571/118650093-a57a9e80-b816-11eb-85e5-5fe111c0e1de.png)

**Comment by Yin-Hongwei** [comment]
跳转是第89行做的，第88行只是设置导航栏首页高亮显示的（好像是来，哈哈哈。
觉得不对的情况看一下浏览器的控制台，可能有报错。

**Comment by gz-j** [comment]
> 跳转是第89行做的，第88行只是设置导航栏首页高亮显示的（好像是来，哈哈哈。
> 觉得不对的情况看一下浏览器的控制台，可能有报错。

多谢，不交换顺序有跳转动作，然后又回到登录界面，也没报错，改完后就好了，哈哈哈
