### ISSUE TITLE
页面无法正常显示数据 后台管理也进不去

### ISSUE THREAD

**Issue by hh857** [Yin-Hongwei/music-website#61]
![image](https://user-images.githubusercontent.com/75458442/118703236-74b35d00-b848-11eb-9d19-8f66ea45aaba.png)
大佬能加个qq聊聊吗 为啥我npm run build --report会出这样的错误，而且我页面没有数据，后台点击登录页面也没有反应

**Comment by Yin-Hongwei** [comment]
3374461366

**Comment by Yin-Hongwei** [comment]
运行的话先启动后端，在启动前端，前端的启动命令是npm run dev
