### ISSUE TITLE
客户端出问题啦

### ISSUE THREAD

**Issue by GHKosovo** [Yin-Hongwei/music-website#62]
![image](https://user-images.githubusercontent.com/26101252/120277953-48d3b500-c2e7-11eb-82d5-61cf5e5c07cc.png)
你好，我部署项目的时候，客户端出错了，如上图
我的node版本：v14.17.0；npm版本：6.14.13
music-manager和music-server都正常
同时，music-client也是可以运行的
![image](https://user-images.githubusercontent.com/26101252/120278410-d3b4af80-c2e7-11eb-842b-708c0f2a57af.png)
但是就是无法点击内容，导航栏也丢失了

**Comment by Yin-Hongwei** [comment]
看着像下载的包有问题，你把node_modules和package-lock.json删了重新npm i一下，然后再启动
