### ISSUE TITLE
网页显示不出来

### ISSUE THREAD

**Issue by Hanyan179** [Yin-Hongwei/music-website#65]
不知道您现在还能看见吗,我用您的代码项目执行了,然后也做了相关步骤,然后
1 后端运行spring命令的时候是一直在运行的状态
2前端的页面也打开了,但是没有数据是数据库连接的错误吗还是别的,
3然后项目后端的mapper文件idea识别不出来数据库表字段

图1
![f6c73c72bf91b7b4c68c5480a3cd3b0](https://user-images.githubusercontent.com/86199539/123262226-3a656b80-d52a-11eb-9738-4955d128b5fe.png)

图2
![f31fb7102a0e3c74519efc554b2d8fa](https://user-images.githubusercontent.com/86199539/123262477-7ef10700-d52a-11eb-9eb0-49b249760018.png)

图3
![1b30b586d8538eae66d840ca3fdf68b](https://user-images.githubusercontent.com/86199539/123262772-d7280900-d52a-11eb-9862-97bbfeb0888a.png)
才上大一因为兴趣弄了一下,结果发现啥也不会
唉,希望您有空能看见

**Comment by Yin-Hongwei** [comment]
看看readme里的步骤配置一下就可以了。后端的虚拟路径没有设置
