### ISSUE TITLE
ws打开的，配置文件都配好了

### ISSUE THREAD

**Issue by antti-ta** [Yin-Hongwei/music-website#66]
![((V{Q89~@DKFSSPU }~7MZD](https://user-images.githubusercontent.com/65747231/123541236-0088a500-d776-11eb-97d6-bb0302f864fa.png)

**Comment by antti-ta** [comment]
我跟前面启动客户端的那哥们问题是差不多的

**Comment by antti-ta** [comment]
![67QUXV_V@9~}@}K TAM1U9A](https://user-images.githubusercontent.com/65747231/123541892-45faa180-d779-11eb-9106-54729bb83cf4.png)

**Comment by antti-ta** [comment]
少了个东西

**Comment by Yin-Hongwei** [comment]
看下readme，目录进的不对。。
