### ISSUE TITLE
music-client里npm install发生报错

### ISSUE THREAD

**Issue by 2w1nd** [Yin-Hongwei/music-website#68]
![image](https://user-images.githubusercontent.com/64266855/126465847-fde9e64c-9239-4943-8260-14efe50dcf51.png)
在npm install的时候发生报错，貌似是python版本的问题
请问python版本要多少呢？

**Comment by Yin-Hongwei** [comment]
和python无关，看一下你node版本

**Comment by 2w1nd** [comment]
![image](https://user-images.githubusercontent.com/64266855/126577511-38bc7166-3727-471e-baed-89d7023206c9.png)
这是node和npm版本

**Comment by 2w1nd** [comment]
解决了，重新clone一下项目就好了，估计之前用的高版本node把项目整乱了
