### ISSUE TITLE
上传头像后图片消失请求报404

### ISSUE THREAD

**Issue by 2w1nd** [Yin-Hongwei/music-website#78]
![image](https://user-images.githubusercontent.com/64266855/134123185-ffc08dd8-5848-4821-86e3-33bae4f751bd.png)
![image](https://user-images.githubusercontent.com/64266855/134123209-45d3f0f4-94fd-473c-894a-9f2e32fa6faa.png)
![image](https://user-images.githubusercontent.com/64266855/134123236-29e36d74-40dd-46f8-b090-dc5a477999b4.png)
上传图片后显示修改成功但请求不到上传后的头像，该如何解决呀？

**Comment by Yin-Hongwei** [comment]
ConsumerController.java 文件里图片路径的处理有问题，上传的时候路径里加了 img，但是数据库里保存路径的时候没加 img，加一下就行了。
