### ISSUE TITLE
为什么只要歌手图片加载不出来？

### ISSUE THREAD

**Issue by Yu-A2020** [Yin-Hongwei/music-website#79]
![image](https://user-images.githubusercontent.com/65153624/134767043-df268a30-a4d3-450d-8b6b-24e51d647bf3.png)
![image](https://user-images.githubusercontent.com/65153624/134767049-74b096da-ea2e-4935-af39-20c152bedc36.png)
![image](https://user-images.githubusercontent.com/65153624/134767059-f702b7ee-d881-4978-890f-f6b645d270ed.png)

**Comment by Yin-Hongwei** [comment]
看一下图片路径放的对不对

**Comment by TestCorn** [comment]
20220214更新内容：
1、windows系统自动读取项目路径，去除代码中的地址硬编码。
2、更改项目结构，便于项目简洁启动
3、修改打印日志级别

可以看下是否解决你的问题呐
