### ISSUE TITLE
VUE不知道为什么跑不起来，我不懂VUE，求帮助。

### ISSUE THREAD

**Issue by FengBang-code** [Yin-Hongwei/music-website#80]
![image](https://user-images.githubusercontent.com/70843366/135758225-61a06110-dc80-420d-b2d6-e638da450fbd.png)
![image](https://user-images.githubusercontent.com/70843366/135758251-947fba6d-b93c-44fe-a0ed-2ea20b3912e6.png)
![image](https://user-images.githubusercontent.com/70843366/135758269-caf929cb-41e1-452e-a61a-88f3fff50e44.png)

**Comment by Yin-Hongwei** [comment]
命令行输一下node -v，看一下 node 版本
