### ISSUE TITLE
歌手图片无法显示 ，我的mac 我改了地址也没办法显示

### ISSUE THREAD

**Issue by hupujrsgit** [Yin-Hongwei/music-website#89]
！[上传image.png...]()
![Uploading image.png…]()

**Comment by TestCorn** [comment]
其实不是代码的问题，应该是当前你下载的文件不全。可以重新下载一下宏伟大佬README.md文件中提供的链接里的文件，重新放进工程里就可以了

**Comment by TestCorn** [comment]
我做了一版优化，现在可以自动读取文件啦，不需要手动再进行地址修改了。
可以拉一下新的代码试下哈~
我测试过Windows环境，Mac环境如果你有电脑的话，麻烦帮看下喔~
