### ISSUE TITLE
关于客户端无法注册的问题

### ISSUE THREAD

**Issue by ColaMk** [Yin-Hongwei/music-website#99]
在管理端可以正常添加用户，在客户端无法注册，点击注册按钮没用响应，浏览器控制台输出"TypeError: __WEBPACK_IMPORTED_MODULE_2__api__.a.handleSignUp is not a function",请问这个是什么问题呢

**Comment by ColaMk** [comment]
![image](https://user-images.githubusercontent.com/90807891/152481981-0fdc1150-9722-4fae-ba81-967dfa36f686.png)

**Comment by Yin-Hongwei** [comment]
更新下代码再

**Comment by ColaMk** [comment]
非常感谢作者！

**Comment by TestCorn** [comment]
这里有个小bug，如果邮箱不填写，有一定的几率会报错。修复中~~~~
